////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    farm
    (
        init
        callBack
        acceptFee
        calculateRewardsForGivenPosition
        claimRewards
        compoundRewards
        end_produce_rewards
        enterFarm
        enterFarmAndLockRewards
        exitFarm
        exitFarmWithNoRewards
        getBurnedTokenAmount
        getCurrentBlockFee
        getDivisionSafetyConstant
        getFarmTokenId
        getFarmTokenSupply
        getFarmingTokenId
        getFarmingTokenReserve
        getLastErrorMessage
        getLastRewardBlockNonce
        getLockedAssetFactoryManagedAddress
        getLockedRewardAprMuliplier
        getMinimumFarmingEpoch
        getOwner
        getPairContractManagedAddress
        getPenaltyPercent
        getPerBlockRewardAmount
        getRewardPerShare
        getRewardReserve
        getRewardTokenId
        getRouterManagedAddress
        getState
        getTransferExecGasLimit
        getUndistributedFees
        mergeFarmTokens
        pause
        recalibrate_farm_token_supply
        registerFarmToken
        resume
        setLocalRolesFarmToken
        setPerBlockRewardAmount
        set_locked_rewards_apr_multiplier
        set_minimum_farming_epochs
        set_penalty_percent
        set_transfer_exec_gas_limit
        start_produce_rewards
        start_produce_rewards_from_nonce
    )
}
